Fixes internap/virtualpdu#30
internap/virtualpdu pull request #32
Opened 2016-11-07 19:11 UTC by idjaw

Exception handling has been added to the libvirt driver's power_off feature. This fixes the issue where an uncaught exception would raise when a power_off command would be issued when the PDU is already off.

2016-11-07 20:19 UTC, fbouliane commented on virtualpdu/tests/unit/drivers/test_libvirt_driver.py
> +DOMAIN_NOT_RUNNING = "internal error: Domain is not running"
should be 

    Requested operation is not valid: domain is not running

2016-11-07 20:22 UTC, fbouliane requested changes
Looks good, small nit

2016-11-07 20:22 UTC, fbouliane commented on virtualpdu/tests/unit/drivers/test_libvirt_driver.py
> +DOMAIN_NOT_RUNNING = "internal error: Domain is not running"
should be

    Requested operation is not valid: domain is not running

2016-11-07 20:24 UTC, fbouliane commented
BTW, test driver does not offer us the capability to test this behavior. A bugfix has been submitted to libvirt to fix this.

2016-11-08 05:14 UTC, mat128 commented on virtualpdu/tests/unit/drivers/test_libvirt_driver.py
> +DOMAIN_NOT_RUNNING = "internal error: Domain is not running"
I would like to see this fixed before merging.

2016-11-08 05:14 UTC, mat128 commented
Thanks fbouliane. I am fine without the integration test.

2016-11-08 16:14 UTC, idjaw commented on virtualpdu/tests/unit/drivers/test_libvirt_driver.py
> +DOMAIN_NOT_RUNNING = "internal error: Domain is not running"
Addressed. Tests running on latest change. Thanks!

2016-11-08 17:44 UTC, fbouliane approved these changes

2016-11-08 18:53 UTC, merged